In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.animation import FuncAnimation

from IPython.display import HTML

from sklearn.cluster import DBSCAN

In [2]:
NAS_ROOT = os.path.join("/", "mnt", "nas", "baecm", "starcraft-vision")
NAS_ROOT

'/mnt/nas/baecm/starcraft-vision'

In [4]:
INPUT_ROOT = os.path.join(NAS_ROOT, "data", "input", "src")
INPUT_ROOT

'/mnt/nas/baecm/starcraft-vision/data/input/src'

In [5]:
ID_STRING = "36.rep"

In [6]:
sample_event = os.path.join(INPUT_ROOT, ID_STRING, "event")

In [62]:
df = pd.read_csv(sample_event)

In [64]:
FPS = 24
def format_mm_ss_ms(frame, fps):
    total_seconds = frame / fps
    minutes = int(total_seconds // 60)
    seconds = total_seconds % 60
    # :05.2f -> 전체 5자리(00.00), 소수점 아래 2자리, 남는 앞자리는 0으로 채움
    return f"{minutes:02d}:{seconds:05.2f}"

In [65]:
df['time'] = df['frame'].apply(lambda x: format_mm_ss_ms(x, FPS))

In [69]:
df['event'].unique().tolist()

['Create', 'Complete', 'Morph', 'Combat', 'Destroy', 'Renegade']

In [66]:
df

,frame,x,y,player,unit,event,time
0,0,1600,48,Neutral,Resource_Mineral_Field,Create,00:00.00
1,0,1600,48,Neutral,Resource_Mineral_Field,Complete,00:00.00
2,0,288,282,rhqpfmaks,Zerg_Larva,Create,00:00.00
3,0,288,282,rhqpfmaks,Zerg_Larva,Complete,00:00.00
4,0,3784,3848,A.X,Protoss_Probe,Create,00:00.00
...,...,...,...,...,...,...,...
75249,28316,1293,1441,rhqpfmaks,Zerg_Zergling,Combat,19:39.83
75250,28319,1315,1453,rhqpfmaks,Zerg_Zergling,Combat,19:39.96
75251,28320,1315,1453,rhqpfmaks,Zerg_Zergling,Combat,19:40.00
75252,28321,1315,1453,rhqpfmaks,Zerg_Zergling,Combat,19:40.04
75253,28322,1315,1453,rhqpfmaks,Zerg_Zergling,Combat,19:40.08

In [58]:
players = df['player'].unique().tolist()
if 'Neutral' in players:
    players.remove('Neutral')
players

['rhqpfmaks', 'A.X']

In [59]:
# t1 = 1000
# t2 = 2000
# df.loc[t1 <= df['frame']].loc[df['frame'] < t2]

In [61]:
df.loc[df['player'] == players[0]].loc[df['frame'] > 0]

       frame     x     y     player           unit     event
273        9   288   281  rhqpfmaks       Zerg_Egg     Morph
275      327   288   281  rhqpfmaks     Zerg_Drone     Morph
276      342   288   274  rhqpfmaks     Zerg_Drone  Complete
277      344   347   240  rhqpfmaks     Zerg_Larva    Create
278      344   347   240  rhqpfmaks     Zerg_Larva  Complete
...      ...   ...   ...        ...            ...       ...
75249  28316  1293  1441  rhqpfmaks  Zerg_Zergling    Combat
75250  28319  1315  1453  rhqpfmaks  Zerg_Zergling    Combat
75251  28320  1315  1453  rhqpfmaks  Zerg_Zergling    Combat
75252  28321  1315  1453  rhqpfmaks  Zerg_Zergling    Combat
75253  28322  1315  1453  rhqpfmaks  Zerg_Zergling    Combat

[37543 rows x 6 columns]